config/routes.rb
Rails.application.routes.draw do


  get 'home/welcome'
  root "home#welcome"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'back/:id', to: 'users#back_project', as: 'back_this_project'
  get 'back/', to: 'users#back', as: 'back_project'
  patch 'back/', to: 'users#back_these'
  get 'unback/:id', to: 'users#unback_project', as: 'unback_this_project'
  get 'join/:id', to: 'users#join_community', as: 'join_this_community'
  get 'leave/:id', to: 'users#leave_community', as: 'leave_this_community'
  resources :projects
  resources :communities
  resources :users
  resources :sessions
  match ":url", to: "application#not_found", :constraints => { :url => /.*/ }, via: [ :get, :post, :patch, :delete ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :projects
    has_many :user_projects
    has_many :backed_projects, through: :user_projects, :source => :project
    has_many :user_communities
    has_many :communities, through: :user_communities
    validates :user_name, uniqueness: {message: "has already been created! Pick a new username."}
    validate :pass_valid?

    attr_reader :password, :password_confirmation

    def pass_valid?
        unless password == password_confirmation && password.length > 6
            errors.add(:password, "must be longer than 6 letters")
        end
    end
# def backed_projects
#     UserProject.all.select{
#         |up|
#         up.user_id == self.id
#     }.collect{
#         |up|
#         up.project
#     }
# end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :get_user, only: [:show]
    before_action :clear_flash, only: [:index, :show, :edit, :new, :back]


    def index
        @users = User.all
    end

    def show 
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_url, notice: "Thank you for signing up!"
        else
            flash[:errors] = @user.errors.full_messages
            render new_user_path
        end
    end

    def edit 
        @user = current_user
    end
    def update
        @user = current_user
        @user.update(user_params)
        UserCommunity.where("user_id=?", @user.id).destroy_all

        community_params["community_ids"].each do |id|
            unless id == ""
                UserCommunity.create(user_id: current_user.id, community_id: id)
            end
        end
        redirect_to user_path(current_user)
    end
    def back_project
        UserProject.create(user_id: current_user.id, project_id: params[:id])
        redirect_to user_path(current_user)
    end
    def join_community
        UserCommunity.create(user_id: current_user.id, community_id: params[:id])
        redirect_to user_path(current_user)
    end
    def back
        @user = current_user

    end
    def back_these
        UserProject.where("user_id=?", current_user.id).destroy_all
        back_params["backed_project_ids"].each do |id|
            unless id == ""
                UserProject.create(user_id: current_user.id, project_id: id)
            end
        end
        redirect_to user_path(current_user)
    end
    def leave_community
        UserCommunity.where(["user_id = ? and community_id = ?", current_user.id, params[:id]]).first.destroy
        flash[:note] = "#{Community.find(params[:id]).name} has been removed from your communities"
        redirect_to user_path(current_user)
    end
    def unback_project
        UserProject.where(["user_id = ? and project_id = ?", current_user.id,  params[:id]]).first.destroy
        flash[:note] = "#{Project.find(params[:id]).name} has been removed from your list!"
        redirect_to user_path(current_user)
    end

    private

    def community_params
        params.require(:user).permit(:community_ids => [])
    end
    def back_params 
        params.require(:user).permit(:backed_project_ids => [])
    end
    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation)
    end
    def get_user
        @user = User.find_by(id: params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/back.html.erb
<%= render 'communities/errors' %>

   

<%= form_with model: @user, url: back_project_path do |f| %>
    
    
    <h3>Back a Project!</h3> 
    Projects: <%= f.collection_check_boxes(:backed_project_ids, Project.all.select{|p| p.status != "Completed"}, :id, :name) do |b| %><br>
                            <label class="container">
                                <%= b.check_box %><span class="checkmark"></span>
                                <label class="check_label"><%= b.label %></label></label>
                            
                    <%end%>
    <br>

    <%= f.submit "Update Projects", :class => "btn-primary btn-sm" %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'communities/errors' %>

   

<%= form_with model: @user do |f| %>

        <%= f.label :user_name %>
        <%= f.text_field :user_name %><br>
        <%= f.label :new_password %>
        <%= f.password_field :password %><br>
        <%= f.label :confirm_new_password %>
        <%= f.password_field :password_confirmation %>

    <h3>Join a new Community!</h3> 
    Communities: <%= f.collection_check_boxes(:community_ids, Community.all, :id, :name) do |b| %><br>
                            <label class="container">
                                <%= b.check_box %><span class="checkmark"></span>
                                <label class="check_label"><%= b.label %></label></label>
                            
                    <%end%>
    <br>

    <%= f.submit "Update Profile", :class => "btn-primary btn-sm" %>

<% end %>

app/views/users/index.html.erb
<h1> All Users </h1>

<ul>
    <% @users.each do |p| %>
    <li> <%= link_to p.user_name, p %></li>
    <% end %>
</ul>

<!-- <%= button_tag link_to "Create a New User", new_project_path %> -->

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    User name: <%= f.text_field :user_name %><br>
    Password: <%= f.password_field :password %><br>
    Password Confirmation: <%= f.password_field :password_confirmation %><br>
    <%= render 'communities/errors' %>
    <%= f.submit "Create Account", :class => "btn-primary btn-sm" %>
    <%end%>

app/views/users/show.html.erb
<h1> <%= @user.user_name %> </h1>

<dl>
    <ul>
    <dt><h3>My Projects</h3></dt> 
        <% if @user.projects.size == 0 %>
        <li style="margin-left: 40px"><%= "No projects yet." %></li>
    <% else %>
        <% @user.projects.each do |project| %>
            <li style="margin-left: 40px"><%= link_to project.name, project %></li>
        <% end %>
    <% end %> 
    </ul>
</dl>

<dl>
    <ul>
    <dt><h3>My Communities</h3></dt>
    <% if @user.communities.size == 0 %>
        <li style="margin-left: 40px"><%= "No communities yet." %></li>
    <% else %>
        <% @user.communities.each do |community| %>
            <li style="margin-left: 40px"><%= link_to community.name, community %></li>
        <% end %>
    <% end %> 
    
    </ul>
</dl>

<dl>
    <ul>
    <dt><h3>Backed Projects</h3></dt>
    <% if @user.backed_projects.size == 0 %>
        <li style="margin-left: 40px"><%= "No backed projects yet." %></li>
    <% else %>
        <% @user.backed_projects.each do |backed_project| %>
            <li style="margin-left: 40px"><%= link_to backed_project.name, backed_project %></li>
        <% end %>
    <% end %> 
    
    </ul>
</dl>

<% if flash[:note] %>
    <div style="color:red"><%= flash[:note]%></div>
<% end %>

<%= link_to "Back a Project", back_project_path, :class => "btn-primary btn-sm" %>
<%= link_to "Edit my Profile", edit_user_path, :class => "btn-primary btn-sm" %>
<%= link_to "Back to Index", users_path, :class => "btn-primary btn-sm" %>
<%= link_to "Create a Project", new_project_path, :class => "btn-primary btn-sm" %>
<%= link_to "Create a Community", new_community_path, :class => "btn-primary btn-sm" %>