config/routes.rb
Rails.application.routes.draw do


  get 'home/welcome'
  root "home#welcome"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'back/:id', to: 'users#back_project', as: 'back_this_project'
  get 'back/', to: 'users#back', as: 'back_project'
  patch 'back/', to: 'users#back_these'
  get 'unback/:id', to: 'users#unback_project', as: 'unback_this_project'
  get 'join/:id', to: 'users#join_community', as: 'join_this_community'
  get 'leave/:id', to: 'users#leave_community', as: 'leave_this_community'
  resources :projects
  resources :communities
  resources :users
  resources :sessions
  match ":url", to: "application#not_found", :constraints => { :url => /.*/ }, via: [ :get, :post, :patch, :delete ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :project_communities, dependent: :destroy
  has_many :communities, through: :project_communities
  
  validates_presence_of :name, {message: "must have a title!"}
  validates :name, uniqueness: {message: "has already been created!"}
  validates :description, length: {minimum: 5, message: "must be longer than 5 characters!"}
  validates :goal, inclusion: {in: 3..5, message: "must be 3 to 5!"}
  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :get_project, only: [:show, :destroy, :edit, :update]
    before_action :authorize, only: [:index]
    before_action :clear_flash, only: [:show, :edit, :new]
    def index
        @status = ["Started", "In Progress", "Completed"]
        if @status.include?(params[:status])
            flash[:status] = params[:status]
            @projects = Project.select{|p| p.status == params[:status]}
            if @projects.size == 0
                @message = "No projects #{params[:status]} yet, back some projects!"
            end
        else
            flash[:status] = "All"
            @projects = Project.all
        end

    end
    def show
    end
    def edit
        if current_user.id != @project.user_id
            redirect_to project_path(@project), alert: "Only the creator can edit this project" 
        else
            render :new
        end
    end
    def update
        if current_user.id != @project.user_id
            redirect_to project_path(@project), alert: "Only the creator can edit this project" 
        else
            ProjectCommunity.where("project_id=?", @project.id).destroy_all
            @project.update(project_params)
            make_project(@project)
        end
    end

    def new
        @project = Project.new(user_id: flash[:user])
    end
    def create

        @project = Project.create(project_params)
        make_project(@project)
    end
    def destroy
        if current_user.id != @project.user_id
            redirect_to project_path(@project), alert: "Only the creator can delete this project" 
        else
            @project.destroy
            redirect_to projects_path
        end
    end

    private

    def make_project(project)
        community_params["community_ids"].each do |id|
            unless id == ""
                ProjectCommunity.create(community_id: id, project_id: @project.id)
            end
        end
        if @project.valid?
            redirect_to "/projects"
        else
            flash[:errors] = @project.errors.full_messages
            redirect_to "/projects/new"
        end
    end

    def get_project
        @project = Project.find(params[:id])
    end
    def project_params
        params.require(:project).permit(
            :name, :description, :goal, :user_id, :status
        )
    end
    def community_params
        params.require(:project).permit(:community_ids => [])
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<h1>
<%= "#{flash[:status]}" %>
</h1>


<%= form_tag '', :method => :get do %>

   <%= select_tag "status", options_for_select([[" -- select --" , "0"]] + [["All" , "0"]] + @status)%>
  <%= submit_tag 'Filter', :class => "btn-primary btn-sm" %>
<% end %>

<%= @message %><br>
<% @projects.each do |p| %>
   <li> <%= link_to p.name, p %></li>
   <p style="margin-left: 20px"> -<%= p.description %> </p>
<% end %>
</ul>
<%= link_to "Create a New Project", new_project_path, :class => "btn-primary btn-sm" %>
<%= link_to "Back a Project", back_project_path, :class => "btn-primary btn-sm" %>

app/views/projects/new.html.erb
<%= form_with model: @project do |f| %>
    Project name: <%= f.text_field :name %><br>
    Description: <%= f.text_field :description %><br>
    Goal: <%= f.number_field :goal %><br>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    Communities: <%= f.collection_check_boxes(:community_ids, Community.all, :id, :name) do |b| %><br>
                            <label class="container">
                            <%= b.check_box %><span class="checkmark"></span>
                            <label class="check_label"><%= b.label %></label></label>
                    <%end%>
                    <br>
    <%= f.hidden_field :status, :value => "Started" %>
    <br>
    <%= render 'communities/errors' %>
    <%= f.submit "Create Project", :class => "btn-primary btn-sm" %>
    <%end%>

app/views/projects/show.html.erb
    <h1><%= @project.name %></h1>
    <p><%= @project.description %></p>

    Status: <%= @project.status %><br><br>
    
    Communities:
    <ul>
    <% if @project.communities.size == 0 %>
        <li><%= "No communities yet." %></li>
    <% else %>
        <% @project.communities.each do |community| %>
            <li><%= link_to community.name, community %></li>
        <% end %>
    <% end %>
    </ul>

    <%= link_to "My Creator", user_path(@project.user), :class => "btn-primary btn-sm" %>
    <%= link_to "Edit Project", edit_project_path(@project), :class => "btn-primary btn-sm" %>
    <% if current_user.backed_projects.include?(@project) %>
    <%=link_to "Un-back Project", unback_this_project_path(@project), :class => "btn-primary btn-sm" %>
    <% else %>
    <%= link_to "Back this Project", back_this_project_path(@project.id), :class => "btn-primary btn-sm" %>
    <% end %>
    <%= link_to "Delete Project",  @project, method: :delete, data: { confirm: "Are you Sure?" }, :class => "btn-primary btn-sm" %>
    <%= render 'communities/errors' %>