config/routes.rb
Rails.application.routes.draw do


  get 'home/welcome'
  root "home#welcome"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'back/:id', to: 'users#back_project', as: 'back_this_project'
  get 'back/', to: 'users#back', as: 'back_project'
  patch 'back/', to: 'users#back_these'
  get 'unback/:id', to: 'users#unback_project', as: 'unback_this_project'
  get 'join/:id', to: 'users#join_community', as: 'join_this_community'
  get 'leave/:id', to: 'users#leave_community', as: 'leave_this_community'
  resources :projects
  resources :communities
  resources :users
  resources :sessions
  match ":url", to: "application#not_found", :constraints => { :url => /.*/ }, via: [ :get, :post, :patch, :delete ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
    has_many :user_communities
    has_many :users, through: :user_communities
    has_many :project_communities, dependent: :destroy
    has_many :projects, through: :project_communities
    validates :name, uniqueness: {message: "has already been created!"}
    validates :name, presence: {message: "must have a name!"}
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :get_id, only: [:show, :edit, :update]
    before_action :authorize, only: [:index]
    before_action :clear_flash, only: [:show, :edit, :new]

    def index
        @communities = Community.all
    end

    def show
    end
    def edit
        @community = Community.find(params[:id])
        if !@community.users.include?current_user
            flash[:note] = "Only members can edit this community"
            redirect_to @community
        end
        #render :edit
    end
    def update
        ProjectCommunity.where("community_id=?", @community.id).destroy_all
        project_params["project_ids"].each do |id|
            unless id == ""
                ProjectCommunity.create(project_id: id, community_id: @community.id)
            end
        end
        redirect_to @community
    end

    def new
        @community = Community.new
    end

    def create
        @community = Community.new(community_params)
        make_community(@community)
        UserCommunity.create(user_id: current_user.id, community_id: @community.id)
        project_params["project_ids"].each do |id|
            unless id == ""
                ProjectCommunity.create(project_id: id, community_id: @community.id)
            end
        end
    end

private
    def make_community(community)
        if @community.valid?
            @community.save
            redirect_to @community
        else
            flash[:errors] = @community.errors.full_messages
            redirect_to new_community_path
        end
    end

    def get_id
        @community = Community.find_by(id: params[:id])
    end

    def community_params
        params.require(:community).permit(:name)
    end
    def project_params
        params.require(:community).permit(:project_ids => [])
    end

end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_errors.html.erb
<% if flash %>
    <% flash.each do |type, message| %>
       <div style="color:red">
            <% if message.class == Array %>
                <% message.each do |m|%>
                    <%= m %><br>
                <%end%>
            <%else%>
                <%= message %>
            <%end%>
       </div><br>
        <%end%>
<%end%>

app/views/communities/edit.html.erb
<h2>  Edit Projects in this Community </h2>

<%= render 'communities/errors' %>

<%= form_with model: @community do |form| %>
    Projects: <%= form.collection_check_boxes(:project_ids, Project.all, :id, :name) do |b| %><br>
                                <label class="container">
                                <%= b.check_box %><span class="checkmark"></span>
                                <label class="check_label"><%= b.label %></label></label>
                            
                    <%end%><br>
    <%= form.submit "Edit Community", :class => "btn-primary btn-sm" %>
<% end %>

app/views/communities/index.html.erb
<h3>Communities </h3>

<ul>
    <% @communities.each do |com| %>
        <li>
        <%= link_to com.name, com %>
        </li>
    <% end %>
</ul>

<%= link_to "Create a New Community", new_community_path, :class => "btn-primary btn-sm" %>

app/views/communities/new.html.erb
<h2> Create a New Community </h2>

<%= render 'communities/errors' %>

<%= form_with model: @community do |form| %>
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
    <br> <br>
    Projects: <%= form.collection_check_boxes(:project_ids, Project.all, :id, :name) do |b| %><br>
                                 <label class="container">
                                <%= b.check_box %><span class="checkmark"></span>
                                <label class="check_label"><%= b.label %></label></label>
                    <%end%>
                    <br>
    <%= form.submit "Create Community", :class => "btn-primary btn-sm" %>
<% end %>

app/views/communities/show.html.erb
<h2><%=@community.name %> </h2>

<dl>
    <dt>All Projects</dt>
    <ul>
        <% @community.projects.each do |project| %>
        <li>
            <%= link_to project.name, project %>
        </li>
        <% end %>
    </ul>
</dl>
<dl>
    <dt>All Users</dt>
    <ul>
        <% @community.users.each do |user| %>
        <li>
            <%= link_to user.user_name, user %>
        </li>
        <% end %>
    </ul>
</dl>

<% if flash[:note] %>
    <div style="color:red"><%= flash[:note]%></div>
<% end %>

<%= link_to "Create a New Project", new_project_path, :class => "btn-primary btn-sm" %>
<%= link_to "Edit Community", edit_community_path(@community), :class => "btn-primary btn-sm" %>
<% if current_user.communities.include?(@community) %>
<%= link_to "Leave Community", leave_this_community_path(@community), :class => "btn-primary btn-sm" %>
<% else %>
<%= link_to "Join this Community", join_this_community_path(@community.id), :class => "btn-primary btn-sm" %>
<% end %>