config/routes.rb
Rails.application.routes.draw do


  get 'home/welcome'
  root "home#welcome"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'back/:id', to: 'users#back_project', as: 'back_this_project'
  get 'back/', to: 'users#back', as: 'back_project'
  patch 'back/', to: 'users#back_these'
  get 'unback/:id', to: 'users#unback_project', as: 'unback_this_project'
  get 'join/:id', to: 'users#join_community', as: 'join_this_community'
  get 'leave/:id', to: 'users#leave_community', as: 'leave_this_community'
  resources :projects
  resources :communities
  resources :users
  resources :sessions
  match ":url", to: "application#not_found", :constraints => { :url => /.*/ }, via: [ :get, :post, :patch, :delete ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
        </button> <%= link_to "HelpOut⏫", root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <li class='nav-item'><%= link_to 'Home', home_welcome_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Projects', projects_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Communities', communities_path, class: 'nav-link' %></li>

                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto">
                <% if current_user %>
                    <li class='nav-item'><%= link_to current_user.user_name, current_user, class: 'nav-link' %></li>
                    <li class='nav-item'><%= link_to "Log Out", new_session_path("current"), method: "delete", class: 'nav-link' %></li>

                <% else %>
                    <li class='nav-item'><%= link_to 'Log in', new_session_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Community Projects" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Communities and their projects" %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main id="content" role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/layouts/communities.html.erb
<% content_for :content do %>
    <div class="jumbotron text-center">
        <h1>Communities</h1>
    </div>
    <div class="containers">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <%= yield %>
                </p>
            </div>
            <div class="col-lg-6">
                <p>

                    <div class="caption">Check out our communities!</div>
                    <img src="https://advising.utah.edu/_images/discover-your-interests-1030x300-cropped.jpg" alt="Working on a Project">
                </p>

            </div>
        </div>
    </div>
    <% end %>
    <%= render template: "layouts/application" %>

app/views/layouts/projects.html.erb
<% content_for :content do %>
    <div class="jumbotron text-center">
        <h1>Projects</h1>
    </div>
    <div class="containers">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <%= yield %>
                </p>
            </div>
            <div class="col-lg-6">
                <p>

                    <div class="caption">Helping the community starts by contributing to projects!</div>
                    <img src="https://www.europeanbusinessmagazine.com/wp-content/uploads/2017/05/Project-Management-service.jpg" alt="Working on a Project">
                </p>

            </div>
        </div>
    </div>
    <% end %>
    <%= render template: "layouts/application" %>